
import gfBaseEvents from '../../../cc30-fishbase/Scripts/Config/gfBaseEvents';
import { mergeTwoObject } from '../../../cc30-fishbase/Scripts/Utilities/gfUtilities';

let EventsCode1988 = {
    PLAYER_LAYER : {
        CHANGE_GUN_DRILL: "CHANGE_GUN_DRILL",
    },
    EFFECT_LAYER: {
        DROP_GUN_DRILL: "DROP_GUN_DRILL",
        DRILL_EXPLOSION: "DRILL_EXPLOSION",
        PLAY_WAVE_TRANSITION_CUSTOM : "PLAY_WAVE_TRANSITION_CUSTOM",
        PLAY_EFFECT_BIGWIN : "PLAY_EFFECT_BIGWIN",
        PLAY_EFFECT_LIGHTING: "PLAY_EFFECT_LIGHTING",
        END_PHASE_POISON_FLOWER: "END_PHASE_POISON_FLOWER",
        REMOVE_DRILL: "EFFECT_LAYER_REMOVE_DRILL",
    },
    GAME_LAYER: {
        CREATE_BULLET_DRILL: "CREATE_BULLET_DRILL",
        RESUME_DRILL: "RESUME_DRILL",
        CLOSE_ALL_MENU: "CLOSE_ALL_MENU",
        BORIS_END: "BORIS_END",
        PLAY_JACKPOT_BORIS : "PLAY_JACKPOT_BORIS",
        RESUME_POISON_FLOWER : "RESUME_POISON_FLOWER",
        UPDATE_PANEL_CHIP: "UPDATE_PANEL_CHIP",
        HIDE_PANEL_CHIP: "HIDE_PANEL_CHIP",
        BORIS_WAIT_DIE: "BORIS_WAIT_DIE"
    },
    FISH_LAYER:{ 
        CREATE_LIST_FISH_FAKE: "CREATE_LIST_FISH_FAKE",
        CATCH_BORIS: "CATCH_BORIS",
        FLOWER_DIE : "FLOWER_DIE",
        BORIS_WAIT_DIE: "BORIS_WAIT_DIE",
        CREATE_CIRCLE_FISH : "CREATE_CIRCLE_FISH",
    },
    SOUND: {
        DRILL_FIRE:  "DRILL_FIRE",
        DRILL_HIT_WALL: "DRILL_HIT_WALL",
        TARGET_LOCK_ONE: "TARGET_LOCK_ONE",
        UI_POPUP: "UI_POPUP",
        FLOWER_EXPLOSION: "FLOWER_EXPLOSION",
        GUN_EQUIP: "GUN_EQUIP",
        WAVE: "WAVE",
        LASER_IDLE: "LASER_IDLE",
        STOP_LASER_IDLE: "STOP_LASER_IDLE",
        BORIS_APPEAR : "BORIS_APPEAR",
        BORIS_WARNING : "BORIS_WARNING",
        BORIS_DIE : "BORIS_DIE",
        BORIS_OUT : "BORIS_OUT",
        BORIS_MOVE : "BORIS_MOVE",
        BORIS_TRASH_TALK : "BORIS_TRASH_TALK",
        CHIP_EQUIP : "CHIP_EQUIP",
        CHIP_DROP : "CHIP_DROP",
        CHIP_FAIL : "CHIP_FAIL",
        CHIP_FLY : "CHIP_FLY",
        LAST_DAMAGE : "LAST_DAMAGE",
        POPUP_JACKPOT : "POPUP_JACKPOT",
        START_COUNTING_LOOP : "START_COUNTING_LOOP",
        STOP_COUNTING_LOOP : "STOP_COUNTING_LOOP",
        BORIS_IDLE : "BORIS_IDLE",
        BORIS_DAMAGE : "BORIS_DAMAGE",
        BORIS_DESTROYED : "BORIS_DESTROYED",
        FLOWER_DIE : "FLOWER_DIE_SOUND",
        POISON_EFFECT : "POISON_EFFECT",
        BORIS_THE_ANIMALS: "BORIS_THE_ANIMALS",
        IT_JUST_BORIS: "IT_JUST_BORIS",
        OPEN_COMPO_AUTO: "OPEN_COMPO_AUTO",
        SELECT_AUTO_MODE: "SELECT_AUTO_MODE",
        CLICK_BUTTON_JOIN_GAME: "CLICK_BUTTON_JOIN_GAME",
        BORIS_LAUGH: "BORIS_LAUGH",
        ACTIVE_PASSWORD: "ACTIVE_PASSWORD"
    },
};

EventsCode1988 = mergeTwoObject(gfBaseEvents, EventsCode1988);
export default EventsCode1988;
